vcom  ../FFT/HDL_DUT_pkg.vhd
vcom  ../FFT/SimpleDualPortRAM_generic.vhd
vcom  ../FFT/SDFCommutator1.vhd
vcom  ../FFT/RADIX22FFT_SDF1_1.vhd
vcom  ../FFT/RADIX22FFT_CTRL1_1.vhd
vcom  ../FFT/SDFCommutator2.vhd
vcom  ../FFT/RADIX22FFT_SDF2_2.vhd
vcom  ../FFT/RADIX22FFT_CTRL1_2.vhd
vcom  ../FFT/TWDLROM_3_1.vhd
vcom  ../FFT/Complex3Multiply.vhd
vcom  ../FFT/SDFCommutator3.vhd
vcom  ../FFT/RADIX22FFT_SDF1_3.vhd
vcom  ../FFT/RADIX22FFT_CTRL1_1_block.vhd
vcom  ../FFT/RADIX2FFT_bitNatural.vhd
vcom  ../FFT/FFT_HDL_Optimized.vhd
vcom  ../FFT/HDL_DUT.vhd
